name: token_manager
description: A token management app with full Firebase Auth & Firestore integration.
version: 1.0.0+1
publish_to: 'none'

# Updated the SDK constraint to support modern Dart 3 features.
# This is a crucial step for compatibility with the latest packages.
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  # State & Storage (Updated to latest versions)
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Utilities (Updated to latest versions)
  excel: ^4.0.6
  intl: ^0.19.0
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  open_filex: ^4.4.0
  device_info_plus: ^9.0.0 # Add this line
  permission_handler: ^11.0.1

  # 🔥 Firebase SDK (Bumped to latest stable versions)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # Package for the custom splash screen
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev dependencies updated for Dart 3
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

  # Package for the app launcher icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # This ensures all images in this folder, including samco_logo.png, are available.
  assets:
    - assets/images/

# Configuration for the App Launcher Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Using app_logo.png for the launcher icon as requested
  image_path: "assets/images/app_logo.png"

# Configuration for the Custom Splash Screen
flutter_native_splash:
  color: "#FFFFFF"  # Sets the background to white.
  # Using splash_screen.png for the splash screen as requested
  image: "assets/images/splash_screen.png"