// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXOZV-7n1kzUIwIHty90GTCIGq-nMZ8c',
    appId: '1:683896291546:web:68f7e00939e37a9cf765e3',
    messagingSenderId: '683896291546',
    projectId: 'restaurantmanagementsyst-7a23c',
    authDomain: 'restaurantmanagementsyst-7a23c.firebaseapp.com',
    storageBucket: 'restaurantmanagementsyst-7a23c.firebasestorage.app',
    measurementId: 'G-9HWPP47YHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9DWj31YtowLXyb0R77tomxLZg8yoPns',
    appId: '1:683896291546:android:de9bc4464620a79ef765e3',
    messagingSenderId: '683896291546',
    projectId: 'restaurantmanagementsyst-7a23c',
    storageBucket: 'restaurantmanagementsyst-7a23c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzw5NSl6hQTTvEAj4hASY-vWUHQklgLc',
    appId: '1:683896291546:ios:cc0bf82a32356782f765e3',
    messagingSenderId: '683896291546',
    projectId: 'restaurantmanagementsyst-7a23c',
    storageBucket: 'restaurantmanagementsyst-7a23c.firebasestorage.app',
    iosBundleId: 'com.example.tokenmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXzw5NSl6hQTTvEAj4hASY-vWUHQklgLc',
    appId: '1:683896291546:ios:cc0bf82a32356782f765e3',
    messagingSenderId: '683896291546',
    projectId: 'restaurantmanagementsyst-7a23c',
    storageBucket: 'restaurantmanagementsyst-7a23c.firebasestorage.app',
    iosBundleId: 'com.example.tokenmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpXOZV-7n1kzUIwIHty90GTCIGq-nMZ8c',
    appId: '1:683896291546:web:346955513265ff4af765e3',
    messagingSenderId: '683896291546',
    projectId: 'restaurantmanagementsyst-7a23c',
    authDomain: 'restaurantmanagementsyst-7a23c.firebaseapp.com',
    storageBucket: 'restaurantmanagementsyst-7a23c.firebasestorage.app',
    measurementId: 'G-WWSS4PZJ1Z',
  );
}
